spring:
  application:
    name: spring-kafka
  kafka:
    bootstrap-servers: "${BOOTSTRAP_SERVER}"


app:
  topics:
    - name: topic1
      partitions: 1
      replicas: 1
    - name: topic2
      partitions: 2
      replicas: 1
